---
title: "Cleaning Seedling Data from Aviation and Strawn"
author: "Camila Vargas"
date: "2/2/2022"
output: html_document
---

## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Load packages
library(here)
library(tidyverse)
library(janitor)
library(readxl)
library(freeR)
library(lubridate)

## Sets R not to use scientific notations
options(scipen=999) 

```

## Exploring data
```{r}

excel_sheets(here::here("6.raw_data/Seedling_Data_Aviation_Strawn.xlsx"))

```

2 sheets found. 
Data contains all necesary data
Key contains metadata info

## Read data
```{r}
aviation_raw <- read_excel(here::here("6.raw_data/Seedling_Data_Aviation_Strawn.xlsx"), sheet = "Data") %>% 
  clean_names()
```

## Exploring
```{r}
colnames(aviation_raw)
range(aviation_raw$date)
str(aviation_raw)

## There are several columns that should be numeric but are character.

unique(aviation_raw$sp)
unique(aviation_raw$island)
unique(aviation_raw$tx)
unique(aviation_raw$hx1) ## replace * with NA 
unique(aviation_raw$dx1)## does * mean something different than NA? only 1 NA variables
unique(aviation_raw$ux1) ## does * mean something different than NA? only 6 NA variables
unique(aviation_raw$lx1) ## Replace * with NA
unique(aviation_raw$damage_type1)
unique(aviation_raw$damage_type2)
unique(aviation_raw$damage_difference) ## replace * with NA
unique(aviation_raw$leaf_difference) ## replace * with NA
unique(aviation_raw$height_difference) ## replace * with NA
unique(aviation_raw$notes)


```


## Cleaning Data
```{r}

aviation_clean <- aviation_raw %>% 
  mutate(across(9:20, ~replace(., . == "*", NA)),
         across(9:12, ~as.numeric(.)),
         across(18:20, ~as.numeric(.)),
         date = date(date)) %>% 
  select(-x22)

## Check
str(aviation_clean)


complete(aviation_clean)
count_na(aviation_raw)

##Checked! NAs in clean data match number of * in Raw data. Only question is if * and NA is the same in variables dx1 and ux1


```

CHECK complete() and make sure no NAs introduced --> Checked!



## Save
```{r}
write_csv(aviation_clean, here::here("7.clean_data/palmyra_aviation_strawn_seedling_data_2005.csv"))

```


